name: Release main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  release:
    name: Create a new production release
    needs: [code-checks]
    uses: ./.github/workflows/_sem_release.yaml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

  publish-docs:
    name: Publish docs to GitHub Pages
    needs: [release]
    uses: ./.github/workflows/_docusaurus_publish.yaml
    secrets:
      docs-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
